name: 'Hello World Action'
description: 'A simple action that says hello'
inputs:
  name:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: "composite"
  steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v4

    - name: Echo stuff
      shell: bash
      run: |
        echo "@@@@ ${{ inputs.name }}"
        pwd
        ls -la
        java -version
        mvn -version




