spring:
  application:
    name: "demo-security"
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driverClassName: org.h2.Driver
logging:
  level:
    org:
      springframework:
        security: TRACE
    com:
      zaxxer:
        hikari: INFO
